# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: allison-truhlar
has_binder: true
has_settings: false
kind: frontend
labextension_name: fileglancer-frontend-ext
project_short_description: React-based frontend extension for the Fileglancer app.
python_name: fileglancer_frontend_ext
repository: https://github.com/JaneliaSciComp/fileglancer
test: true

