# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: allison-truhlar
has_binder: true
has_settings: false
kind: server
labextension_name: fileglancer-server
project_short_description: Browse, share, and publish files on the Janelia file system
python_name: fileglancer_server
repository: https://github.com/JaneliaSciComp/fileglancer
test: true

