"""create task data table

Revision ID: c05fd0a62deb
Revises: 9812335c52b6
Create Date: 2025-11-12 10:53:48.450263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05fd0a62deb'
down_revision = '9812335c52b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('proxy', sa.String(), nullable=True),
    sa.Column('parameters', sa.String(), nullable=True),
    sa.Column('compute_resources', sa.String(), nullable=True),
    sa.Column('monitor_url', sa.String(), nullable=True),
    sa.Column('output_log', sa.String(), nullable=True),
    sa.Column('error_log', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###