# Default Fileglancer OME-Zarr Viewers Configuration
# Can be overridden by providing a custom viewers.config.yaml file in the frontend/ directory

viewers:
  - manifest_url: 'https://raw.githubusercontent.com/JaneliaSciComp/fileglancer/viewers-config/frontend/public/viewers/neuroglancer.yaml'

  - manifest_url: 'https://raw.githubusercontent.com/JaneliaSciComp/fileglancer/viewers-config/frontend/public/viewers/avivator.yaml'

  - manifest_url: 'https://raw.githubusercontent.com/JaneliaSciComp/fileglancer/viewers-config/frontend/public/viewers/validator.yaml'

  - manifest_url: 'https://raw.githubusercontent.com/JaneliaSciComp/fileglancer/viewers-config/frontend/public/viewers/vole.yaml'
